fix: Add ability to edit avatar
calcom/cal.diy pull request #11399
Opened 2023-09-16 10:36 UTC by samueldenzil

## What does this PR do?

Added ability to edit the avatar.

Fixes #11376 

[screencast_2023-09-16_15-38-19.mov](https://github.com/calcom/cal.com/assets/71846487/2e1773a9-adc8-46d6-8775-c2d963b06dc0)

I've also added spacing of 4px between username and email.

![Screenshot from 2023-09-16 15-41-59 1](https://github.com/calcom/cal.com/assets/71846487/1145a856-6a48-471e-b785-e6feee840b8e)

2023-09-16 10:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=11399) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=11399) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=11399) it.</sub>

2023-09-22 07:47 UTC, Udit-takkar commented on packages/features/users/components/UserTable/EditSheet/EditUserForm.tsx
> +                    console.log(value);
NIT: remove this

2023-09-22 07:47 UTC, Udit-takkar commented on packages/features/users/components/UserTable/EditSheet/EditUserForm.tsx
> +                  buttonMsg="Change avatar"
use i18n here

2023-09-22 09:11 UTC, Udit-takkar requested changes
https://github.com/calcom/cal.com/assets/53316345/886d9b81-980f-4ef5-b0ca-9090c767427c

2023-09-22 09:22 UTC, samueldenzil commented
> Screen.Recording.2023-09-22.at.2.40.02.PM.mov

This behaviour was happening before adding the avatar edit option. You must select the "role" first (for testing I was using the Admin role), then the update button works.

2023-09-22 12:05 UTC, Udit-takkar commented
@samueldenzil  I don't this we should change the role of "OWNER", just to update the avatar.  i pushed some changes to fix the issue.

2023-09-22 12:06 UTC, Udit-takkar approved these changes
LGTM

2023-09-22 23:12 UTC, merged